[build-system]
requires = ["flit-core>=3.12.0"]
build-backend = "flit_core.buildapi"

[project]
name = "slyp"
version = "0.9.0"
description = "Stephen Lints Your Python"
readme = "README.md"
requires-python = ">=3.10"
license = { "text" = "MIT" }
keywords = []
authors = [
  { name = "Stephen Rosen", email = "sirosen@globus.org" },
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
    "libcst>=1",
    'typing_extensions>=4.0; python_version<"3.11"'
]

[project.urls]
source = "https://github.com/sirosen/slyp"

[project.scripts]
slyp = "slyp:main"


[dependency-groups]
coverage = ["coverage"]
test = ["pytest", {include-group = "coverage"}]
benchmark = ["pytest", "pytest-codspeed"]
mypy = ["mypy"]
docs = [
  "sphinx<8",
  "sphinx-issues<5",
  "furo==2024.7.18",
]


[tool.check-sdist]
git-only = [".gitignore", "docs/*"]

[tool.flit.sdist]
include = [
  "changelog.rst",
  "tests/**/*.py",
  "tests/**/*.txt",
  "tox.ini",
  ".flake8",
  "justfile",
]
exclude = ["**/.*", "**/*.egg-info", "**/__pycache__"]


[tool.coverage.run]
parallel = true
source = ["slyp"]
[tool.coverage.paths]
source = [
    "src/",
    "*/site-packages/"
]
[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_lines = [
    # the pragma to disable coverage
    "pragma: no cover",
    # don't complain if tests don't hit unimplemented methods/modes
    "raise NotImplementedError",
    # don't check on executable components of importable modules
    "if __name__ == .__main__.:",
    # mypy-only code segments
    "if t.TYPE_CHECKING:",
    # type-checking overloads
    "@t.overload"
]
[tool.isort]
profile = "black"
[tool.mypy]
strict = true
[tool.pytest.ini_options]
norecursedirs = ["tests/benchmark"]
filterwarnings = ["error"]
