name: build
on:
  push:
  pull_request:

jobs:
  run-other-tox-env:
    strategy:
      matrix:
        toxenv: [mypy, lint]
        py: ["3.14"]

    runs-on: ubuntu-latest
    name: "Run '${{ matrix.toxenv }}' on python ${{ matrix.py }}"
    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false

        - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
          with:
            python-version: "${{ matrix.py }}"

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

      - name: install tox
        run: uv tool install tox --with tox-uv

      - name: setup tox environment
        run: tox run -e  "${{ matrix.toxenv }}" --notest -vv

      - name: run
        run: tox run -e "${{ matrix.toxenv }}"

  ci-test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py: ['3.10', '3.11', '3.12', '3.13', '3.14']
    name: "Run tests on ${{ matrix.os }}, py${{ matrix.py }}"
    runs-on: ${{ matrix.os }}
    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false

        - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
          with:
            python-version: "${{ matrix.py }}"

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

      - run: uv tool install tox --with tox-uv

      - name: cache tox virtualenvs
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .tox
          key: >
            tox
            os=${{ runner.os }}
            python=${{ steps.setup-python.outputs.python-version }}
            hash=${{ hashFiles('.github/workflows/build.yaml', 'pyproject.toml', 'tox.ini') }}

      - name: setup tox environment
        run: tox run -e  py --notest -vv

      - name: test
        run: tox run -e py
