name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmark:
    name: run benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # required for OIDC authentication with CodSpeed
      id-token: write

    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

        - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
          with:
            python-version: "3.14"

      - name: install tox
        run: uv tool install tox --with tox-uv

      - name: cache tox virtualenvs
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .tox
          key: >
            tox
            os=${{ runner.os }}
            hash=${{ hashFiles('.github/workflows/codspeed.yaml', 'pyproject.toml', 'tox.ini') }}

      - name: setup tox environment
        run: tox run -e benchmark --notest -vv

      - name: benchmark
        uses: CodSpeedHQ/action@c4fd08a3a159bd0cc208da1e0edf32b8c47d75e5 # v5.4.0
        with:
          mode: simulation
          run: tox run -e benchmark
