name: Publish Test PyPI Release

on:
  push:
    tags: ["*"]

jobs:
  build-dists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python -m pip install build twine

      - name: Build Dists
        run: python -m build .

      - name: Check Dists (twine)
        run: twine check dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: dist/*


  publish:
    needs: [build-dists]
    runs-on: ubuntu-latest
    environment: publish-testpypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
